apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: azeem-eks-1
  region: us-east-1


# eksctl create cluster --name azeem-eks-1 --version 1.25 --nodegroup-name ng-1 --node-type t3.micro --nodes 2
nodeGroups:
- name: ng-1
  instanceType: t3.micro
  minSize: 1
  maxSize: 4
  desiredCapacity: 2

# eksctl create cluster --name azeem-eks-1 --version 1.25 --nodegroup-name ng-2 --node-type t3.micro --nodes 2 --managed


#imp - kubectl config get-contexts lec-23 starting
