version: '3'
services:
  jenkins:
      container_name: myJenkins
      # image: jenkins/jenkins
      build:
        context: Docker-Image/jenkins-docker-image
      restart: on-failure
      ports:
        - "8001:8080"
      volumes:
        - $PWD/jenkins-home:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
      # command: bash -c "chmod 666 /var/run/docker.sock"
      networks:
        - net
  sonarqube:
    container_name: mySonarQube
    image: sonarqube
    ports:
      - 9000:9000
    networks:
      - net
    
networks:
  net: